Update vacuumpump/ADOPTERS.yaml
smart-data-models/dataModel.RoboticIndustrialActivities pull request #5
Opened 2021-05-13 06:30 UTC by OptidriveAdmin

2021-05-17 07:05 UTC, albertoabellagarcia commented on VacuumPump/ADOPTERS.yaml
>  description: This is a compilation list of the current adopters of the data model [Data model] of the Subject [Subject].  All fields are non mandatory. More info at https://smart-data-models.github.i
Cannot be this a bit more precise?

2021-05-17 08:29 UTC, OptidriveAdmin reviewed
I prepared a new file. Do i have to create a new patch or how can i edit and improve the adopter.yaml file in this patch?

2021-05-17 09:03 UTC, albertoabellagarcia commented
up to you both alternatives are nice

2021-05-24 10:15 UTC, albertoabellagarcia requested changes
Please include more info about the use case

2021-05-25 11:40 UTC, albertoabellagarcia approved these changes

2021-05-25 11:40 UTC, merged